spring.application.name=crud

#Postgresql Connection
spring.datasource.url = jdbc:postgresql://localhost:5432/crud_database
spring.datasource.username = postgres
spring.datasource.password = mysql1234
