spring.application.name=crud

#Postgresql Connection
spring.datasource.url = jdbc:postgresql://localhost:5432/crud_database
spring.datasource.username = postgres
spring.datasource.password = mysql1234

#JPA Settings
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
